# Generated by Django 6.0 on 2026-01-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
    ]
